# Generated by Django 3.1 on 2021-02-05 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_store_name', models.CharField(max_length=100)),
                ('seller_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('Category', models.CharField(choices=[('elec', 'Electronics'), ('fas', 'Fashion'), ('app', 'Home and Appliances'), ('book', 'Books and Magazines')], max_length=255)),
                ('product_info', models.CharField(max_length=516)),
                ('price', models.FloatField(max_length=10)),
                ('product_img', models.ImageField(upload_to='product_images/')),
                ('store_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.store')),
            ],
        ),
    ]
